_format_version: "3.0"

services:
  - name: auth-service
    url: http://auth-service:3001
    routes:
      - name: auth-routes
        paths:
          - /api/auth
        strip_path: true
        methods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
    plugins:
      - name: rate-limiting
        config:
          minute: 500
          hour: 5000
          policy: local
      - name: cors
        config:
          origins:
            - "*"
          methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          headers:
            - Accept
            - Authorization
            - Content-Type
            - Accept-Language
            - X-Requested-With
          exposed_headers:
            - X-Auth-Token
          credentials: true
          max_age: 3600
          preflight_continue: false

  - name: user-service
    url: http://user-service:3002
    routes:
      - name: user-routes
        paths:
          - /api/users
        strip_path: true
        methods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
    plugins:
      - name: rate-limiting
        config:
          minute: 500
          policy: local
      - name: cors
        config:
          origins:
            - "*"
          methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          headers:
            - Accept
            - Authorization
            - Content-Type
          credentials: true
          max_age: 3600

  - name: score-service
    url: http://score-service:3003
    routes:
      - name: score-routes
        paths:
          - /api/scores
        strip_path: true
        methods:
          - GET
          - POST
          - PUT
          - OPTIONS
    plugins:
      - name: rate-limiting
        config:
          minute: 500
          policy: local
      - name: cors
        config:
          origins:
            - "*"
          methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          headers:
            - Accept
            - Authorization
            - Content-Type
          credentials: true
          max_age: 3600

  - name: ranking-service
    url: http://ranking-service:3004
    routes:
      - name: ranking-routes
        paths:
          - /api/rankings
        strip_path: true
        methods:
          - GET
          - OPTIONS
    plugins:
      - name: rate-limiting
        config:
          minute: 500
          policy: local
      - name: cors
        config:
          origins:
            - "*"
          methods:
            - GET
            - OPTIONS
          headers:
            - Accept
            - Authorization
            - Content-Type
          credentials: true
          max_age: 3600
      - name: response-transformer
        config:
          add:
            headers:
              - X-Cache-Status:HIT

  - name: game-catalog-service
    url: http://game-catalog-service:3005
    routes:
      - name: game-catalog-routes
        paths:
          - /api/games
          - /api/tags
        strip_path: true
        methods:
          - GET
          - OPTIONS
    plugins:
      - name: rate-limiting
        config:
          minute: 500
          policy: local
      - name: cors
        config:
          origins:
            - "*"
          methods:
            - GET
            - OPTIONS
          headers:
            - Accept
            - Authorization
            - Content-Type
          credentials: true
          max_age: 3600

# Global plugins
plugins:
  - name: prometheus
    config:
      status_code_metrics: true
      latency_metrics: true
      bandwidth_metrics: true
      upstream_health_metrics: true
